stages:
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ykltest
      pushRemote: true
      registry: 10.13.33.32:5000
    when:
      event:
        include:
        - push
timeout: 15
branch:
  include:
  - master
notification:
  recipients:
  - recipient: 闫凯龙
    notifier: c-zkkj2:n-tnzz5
  condition:
  - Success
  - Changed
  - Failed
